default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

credentials: &credentials
  username: postgres
  password: ''

development:
  <<: *default
  <<: *credentials
  database: bbva_demo_development

test:
  <<: *default
  <<: *credentials
  database: bbva_demo_test

production:
  <<: *default
  database: bbva_demo_production
